apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "little-goldie.main.serviceAccountName" . }}
  labels:
    {{- include "little-goldie.labels" . | nindent 4 }}
    {{- include "little-goldie.main.selectorLabels" . | nindent 4 }}
  {{- with .Values.main.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

